# Configuration for release-drafter workflow
# Documentation : https://github.com/marketplace/actions/release-drafter
name-template: 'v$NEXT_MINOR_VERSION'
#tag-template: 'v$NEXT_MINOR_VERSION'
commitish: 'dev'
categories:
  - title: 'ğŸš€ Features'
    label: 'feature'
  - title: 'ğŸ› Bugs'
    label: 'bug'
  - title: 'Documentation'
    label: 'documentation'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  ## Changes $NEXT_MINOR_VERSION

  $CHANGES

